### PR TITLE
Search functionality for website documentation

### PR DESCRIPTION
**Pull request by pksrc**
## Summary

Adding the ability to search VEBA website documentation for new users and return users to quickly find the information that they are looking for. Search is implemented using github pages friendly [tipuesearch](https://github.com/jekylltools/jekyll-tipue-search) which I've customized for our website to index external content (blogs within the docs menu) 

## Pull Request Checklist

- [x] Please ensure that you are making a pull request against the **Development** branch
- [x] Please use the `WIP` keyword in the title of your PR if change is not ready to be merged
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [x] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commmits related to your change

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

* Issue Numbers: #177 

## Testing Verification

* Tested by deploying to https://veba.pdotk.com/kb/ and obtained initial feedback from @rguske and @kremerpatrick 

## Additional Information

* Any other details you wish to include or mention

### CODE REVIEW

**Comment by pksrc** [comment]
thanks @lamw , i've squashed the commit for this change, removed the WIP from title and removed the cname change.

**Comment by embano1** [comment]
What's the status of this PR?

**Comment by pksrc** [comment]
It needs to be merged. I think we were waiting for you to double check and see if you had any thoughts or questions on the change.

**Comment by embano1** [comment]
LGTM

**Pull request merged**
