### PR TITLE
Added replacing existing cert instructions

### LINKED ISSUE #472: Restore manual certificate instructions
Commit 5e7c2e46423f97b7aa227ca2494a50eba0f3e245 changed /docs/kb/advanced-certificates.md to align with the new OVA UI method of deploying a new SSL certificate. However, the original instructions are necessary in the event that you need to replace the existing cert that you deployed through the OVA UI. 

We need to restore the original instructions under a certificate replacement section of the document.

### PR DESCRIPTION
**Pull request by kremerpatrick**
Signed-off-by: Patrick Kremer <pkremer@vmware.com>

## Summary

Updates docs to include section on how to replace an existing SSL certificate keypair

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [ ] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [ ] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X ] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

Closes #472 

## Testing Verification

Viewed the rendered .md file

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

### CODE REVIEW

**Comment by embano1** [comment]
LGTM @kremerpatrick thx. But can you please reword the commit to `docs: Add replace TLS cert instructions` so it renders nicely in the CHANGELOG/release notes?

**Review by embano1 — DISMISSED** [review]
LGTM and approved.

One minor addition might be though to verify whether it worked, e.g. by listing the HTTPproxy instances and check whether they're showing valid. Let me know if you want to add this or feel free to merge.

**Comment by kremerpatrick** [comment]
Added HTTPproxy check as suggested.

**Review by embano1 — APPROVED** [review]
THX!

**Pull request merged**
