### PR TITLE
Updating style for headers and TOC for Event Router page

### PR DESCRIPTION
**Pull request by pksrc**
Signed-off-by: pksrc <kandasamyp@vmware.com>

## Summary

Please describe your changes and what you plan to introduce as part of this pull request submission. If it fixes a bug or resolves a feature request, be sure to link to the issue numbers following the template below.

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [ ] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [x] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

Closes Issue with website Header UI rendering. 

## Testing Verification

* Website tested locally. Additionally, here is the screenshot for how the headers render with the new styling. 
image

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

### CODE REVIEW

**Comment by embano1** [comment]
Thx PK! LGTM, I just have one ask since we're copying the contents of the router markdown from the Github page, should we also change the headings in that doc? Otherwise your changes (decrease level of headings in configuration and following sections) would be overwritten again.

**Comment by pksrc** [comment]
Good catch, I'll update the MD to match these changes so there is consistency.

**Comment by embano1** [comment]
Ping @pksrc any ETA so we can get this in for v0.7.1? 🙏

**Comment by pksrc** [comment]
Sorry for the delay! Completely missed this in the midst of other things. I'm looking at this now.

**Review by embano1 — COMMENTED** [review]
LGTM! Can you please change the commit title/message following our format:

```console
git commit -s -m "docs: Update style headers" -m "Closes: 733"
```

**Comment by pksrc** [comment]
Done

**Comment by embano1** [comment]
Awesome sir!

**Review by embano1 — APPROVED** [review]

**Pull request merged**
