### PR TITLE
PS server.ps1 return "Bad Request" on invalid cloud event

### LINKED ISSUE #459: [BUG] PowerShell Server accepts invalid CloudEvent
**Describe the bug**

The CloudEvent parsing logic in `server.ps1` seems to be incorrect, incorrectly returning a CE even though the input is invalid.

**To Reproduce**

Create basic `handler.ps1`

```powershell
Function Process-Init {
   Write-Host "$(Get-Date) - Processing Init"

   Write-Host "$(Get-Date) - Init Processing Completed"
}

Function Process-Shutdown {
   Write-Host "$(Get-Date) - Processing Shutdown"

   Write-Host "$(Get-Date) - Shutdown Processing Completed"
}

Function Process-Handler {
   param(
      [Parameter(Position = 0, Mandatory = $true)][CloudNative.CloudEvents.CloudEvent]$CloudEvent
   )
   
   Write-Host "$(Get-Date) - Processing incoming request"
   Write-Host ($CloudEvent | Format-Table | Out-String)
   Write-Host "$(Get-Date) - Processing done"
}
```

Send dummy data via `curl -v -d '{"hello":"world"}' localhost:8080`.
Returns:

```console
06/24/2021 07:17:25 - Processing incoming request

DataContentType                   Data                 Id DataSchema Source SpecVersion Subject Time Type
---------------                   ----                 -- ---------- ------ ----------- ------- ---- ----
application/x-www-form-urlencoded {123, 34, 104, 101…}                             V1_0
```

**Expected behavior**

Do not execute handler and reject (raise exception?) invalid input.

**Screenshots**

**Version (please complete the following information):**

```Dockerfile
FROM projects.registry.vmware.com/veba/ce-ps-base:1.1
ENV TERM linux
ENV PORT 8080

COPY handler.ps1 handler.ps1

CMD ["pwsh","./server.ps1"]
```

**Additional context**

### PR DESCRIPTION
**Pull request by dmilov**
Signed-off-by: Dimitar Milov <dmilov@vmware.com>

## Summary
Update PowerShell server.ps1 to return 'Bad Request' response in case request is not a valid cloud event.

Fixes issue #459

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [ ] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

Closes #459

## Testing Verification

* Short summary of testing (e.g. successfully built and deployed VMware Event Broker Appliance)
* Please include any relevant screenshots and/or output as part of the testing

- Ran server.ps1 locally
- Client sends a request to the server which is not a cloud event
- Result in the client
```powershell
Line |
   9 |      Invoke-WebRequest -Uri $serverUrl -Body "{'hello': 'world'}"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 400 (Bad Request).  
```

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

### CODE REVIEW

**Comment by dmilov** [comment]
> 
> 
> The PR has conflicts, did you pull/rebase before filing this one?

I did. Let me check again, probably did something wrong.

**Comment by dmilov** [comment]
> 
> 
> > The PR has conflicts, did you pull/rebase before filing this one?
> 
> I did. Let me check again, probably did something wrong.

My bad. fixing.

**Comment by embano1** [comment]
FYI: Found another issue, might be SDK related though: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/543

**Review by embano1 — APPROVED** [review]
LGTM

**Comment by embano1** [comment]
@dmilov before I merge can you please reword your commit message to something like `fix: Return 400 on invalid CloudEvent`?

**Review by embano1 — APPROVED** [review]
LGTM

**Pull request merged**
