### PR TITLE
Fix PowerShell unescaped hyphen in JSON issue

### LINKED ISSUE #196: Hostmaint-alarms fails on hosts where the cluster name contains a hyphen with a preceeding space
**Bug Description**
If a cluster name has a space followed by a hyphen, the cluster name isn't being passed to the script in a way that prevents the script from thinking argument switches are being used.

If a host has a hyphen in it's hostname, an error is thrown when an exit or enter event is processed. It appears the command line for powershell may be interpreting the hyphens as command line switches. The exact error:

**Steps to reproduce the behavior:**
1. Place a host in a cluster named similar to "AAA201 - LAB"  into maintenance mode. The following error would occur:
> /root/function/script.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
> + CategoryInfo          : InvalidArgument: (:) [script.ps1], PSArgumentException
> + FullyQualifiedErrorId : Argument,script.ps1
2. Place a host in a cluster named similar to "AAA201 -LAB" into maintenance mode. The following error would occur:
> ConvertFrom-Json : Conversion from JSON failed with error: Invalid character after parsing property name. Expected ':' but got: {. Path 'data.ComputeResource.Name', line 3, position 0.
> At /root/function/script.ps1:9 char:17
> + $json = $args | ConvertFrom-Json
> +                 ~~~~~~~~~~~~~~~~
> + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
> + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
> 
> DEBUG: json=""
> Connecting to vCenter Server ...
> 
> Get-View : 08/25/2020 16:04:54  Get-View                View with Id  '-' was not found on the server(s).
> At /root/function/script.ps1:26 char:14
> + $hostMoRef = Get-View $moRef
> +              ~~~~~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (:) [Get-View], VimException
> + FullyQualifiedErrorId : Core_GetView_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.DotNetInterop.GetVIView

3. Place a host in a cluster named similar to "AAA201- LAB" into maintenance mode. Script executes as expected.
4. Place a host in a cluster named similar to "AAA201-LAB" into maintenance mode. Script executes as expected.

**Expected behavior**
The name of the cluster being passed along should be enveloped to prevent spaces and hyphens from being evaluated as arguments. 

**Version:**
 - VEBA Form Factor: Appliance
 - VEBA Version: v0.4.1

### PR DESCRIPTION
**Pull request by kremerpatrick**
Signed-off-by: Patrick Kremer <pkremer@vmware.com>

## Summary

User reports PowerShell erroring out when cluster names contain a hyphen and space. As I researched this, I discovered that this PowerShell problem appeared anytime there was a space and a hyphen anywhere in the JSON. This fix changes the xargs command in the fprocess variable to include the JSON within double-quotes. PowerShell then treats the hyphens as a string and not a command-line argument. Thanks to @pksrc for helping me locate the correct spot to make the change.

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [ X] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [X] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [X ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commmits related to your change
- [ X] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

Closes #196 
* Closes #ISSUE-NUMBER

## Testing Verification

* Short summary of testing (e.g. successfully built and deployed VMware Event Broker Appliance)
* Please include any relevant screenshots and/or output as part of the testing
Tested on VEBA 0.4.0. Successfully enabled and disabled alarms when exiting and entering maintenance mode on a cluster with and without space-hyphen in the name. 

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

### CODE REVIEW

**Comment by pksrc** [comment]
FYI, this might also have to be fixed in OpenFaaS's templates. Or we must make sure that our users deploying from the examples are using the modified template that you've fixed.

**Comment by kremerpatrick** [comment]
Will need to discuss with the VEBA team, there is no PowerCLI template that I can find for OpenFaaS. I found a PowerShell HTTP template but it doesn't match the PowerCLI template.yml. Not sure where the PowerCLI template came from.

**Comment by embano1** [comment]
@rguske I think you checked on the PCLI template last time. @pksrc is right, we need to fix this in the template and not just the copy of the template we have stored in the repo here.

**Comment by lamw** [comment]
@kremerpatrick There was never an official PowerCLI OpenFaaS template, as PCLI is merely an application that is installed on top of base PowerShell OF Template (which was original sourced from https://github.com/openfaas-incubator/powershell-template/tree/master/template/powershell). 

Based on our needs/examples, I created both PowerShell and PowerCLI examples where the former doesn't include PowerCLI Module. Its been awhile, but I believe you need to also update the actual Dockerfile (which is where the functions are built from) and simply updating template.yml isn't sufficient.

**Comment by kremerpatrick** [comment]
I can change the Dockerfile for consistency if you like, but it has no effect. That was the original problem, I'd change the Dockerfile, rebuild, and the fprocess environment variable remained as the wrong value xargs pwsh ./function/script.ps1, because that's what was in template.yml

Whatever is in template.yml is what shows up as the fprocess environment variable in the pod.

**Comment by kremerpatrick** [comment]
Did additional testing with this change, fprocess in template.yml overrides anything in the Dockerfile. But I made the Dockerfile match template.yml

**Comment by embano1** [comment]
Just throwing this out: should we create our own "VEBA" PCLI template?

**Comment by embano1** [comment]
Will be closed when we address #209

**Pull request closed without merging**
