### PR TITLE
Add official VEBA mascot

### PR DESCRIPTION
**Pull request by rguske**
Signed-off-by: Robert Guske <rguske@mware.com>

### CODE REVIEW

**Comment by lamw** [comment]
@rguske Very minor nit, not sure if its your keyboard settings but I noticed the apostrophe character in `I'm` looks a bit different? Let me know if you'd like to fix or look into it, if not I can merge

**Comment by embano1** [comment]
can you please squash into one commit before merging @rguske?

**Comment by embano1** [comment]
Totally forgot to ask: do we want the logo also on the start page of the repo?

**Comment by rguske** [comment]
Would be an eye-catcher. You should do this 👍

**Comment by embano1** [comment]
@rguske done #101

**Pull request merged**
