### PR TITLE
Update setup scripts to support multi-event providers

### PR DESCRIPTION
**Pull request by lamw**
Closes: #516
Signed-off-by: William Lam <wlam@vmware.com>

## Summary

This change introduces a basic framework to VEBA setup scripts to be able to support multiple-event providers running within a single VEBA appliance. Since there is a 1:1 mapping between VMware Event Router and a given Event Provider, the deployments and various configuration files/entries will now contain a suffix of the provider(s) (e.g. `vcenter`) that have been enabled as you can see in output below:

```console
root@veba [ ~ ]# kubectl -n vmware-system get all
NAME                                               READY   STATUS    RESTARTS   AGE
pod/cadvisor-txnwn                                 1/1     Running   0          2m45s
pod/tinywww-dd88dc7db-5j9h6                        1/1     Running   0          2m48s
pod/veba-rabbit-server-0                           1/1     Running   0          3m31s
pod/veba-ui-54967b4bf4-668nl                       1/1     Running   0          2m46s
pod/vmware-event-router-vcenter-6d87d466d6-5jlvl   1/1     Running   3          3m31s

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
service/cadvisor                      ClusterIP   10.99.243.57    <none>        8080/TCP             2m45s
service/tinywww                       ClusterIP   10.107.243.56   <none>        8100/TCP             2m48s
service/veba-rabbit                   ClusterIP   10.102.74.32    <none>        5672/TCP,15672/TCP   3m31s
service/veba-rabbit-nodes             ClusterIP   None            <none>        4369/TCP,25672/TCP   3m31s
service/veba-ui                       ClusterIP   10.107.76.10    <none>        80/TCP               2m46s
service/vmware-event-router-vcenter   ClusterIP   10.109.28.162   <none>        8082/TCP             3m32s

NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/cadvisor   1         1         1       1            1           <none>          2m45s

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tinywww                       1/1     1            1           2m49s
deployment.apps/veba-ui                       1/1     1            1           2m46s
deployment.apps/vmware-event-router-vcenter   1/1     1            1           3m32s

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/tinywww-dd88dc7db                        1         1         1       2m49s
replicaset.apps/veba-ui-54967b4bf4                       1         1         1       2m46s
replicaset.apps/vmware-event-router-vcenter-6d87d466d6   1         1         1       3m32s

NAME                                  READY   AGE
statefulset.apps/veba-rabbit-server   1/1     3m31s
```

With the potential for multiple VMware Event Router's running, we also need to have a unique endpoint for stats for each provider. Previously, to get to stats, you'd enter `https://veba-fqdn/stats` and the new URL will be `https://veba-fqdn/stats/provider` where the current supported provider is `vcenter`

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [ ] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [ ] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe):

## Testing Verification

* Successfully built & deployed VEBA Appliance with default (`vcenter`) provider and ensure no change in behavior for setup scripts

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

### CODE REVIEW

**Review by embano1 — COMMENTED** [review]
Overall looks good, just minor feedback:

- Is there no way to collapse the ingress definitions into one file since we're using a templating engine? I feel there's still a lot of redundancy which makes reviews and troubleshooting harder. I thought this could be solved with ytt?
- Somewhat inconsistent use of naming, e.g. "vmware-event-router..." vs "event-router..." in ingress and config definitions. Was a bit hard to review the different files due to these inconsistencies

**Comment by lamw** [comment]
> Overall looks good, just minor feedback:
> 
> * Is there no way to collapse the ingress definitions into one file since we're using a templating engine? I feel there's still a lot of redundancy which makes reviews and troubleshooting harder. I thought this could be solved with ytt?
> * Somewhat inconsistent use of naming, e.g. "vmware-event-router..." vs "event-router..." in ingress and config definitions. Was a bit hard to review the different files due to these inconsistencies

1) I was going to tackle the ingress consolidation as a separate PR but might be good idea just to get that done now. Let me take another look

2) Agreed. I actually preserved the original naming but this was also painful for updating scripts. Let me consolidate the name and simply use `vmware-event-router-*` for everything, which should also simplify the code :)

**Comment by lamw** [comment]
Incorporated all feedback!

**Review by embano1 — APPROVED** [review]
LGTM! Did you verify an OpenFaaS installation as well?

**Comment by lamw** [comment]
> LGTM! Did you verify an OpenFaaS installation as well?

Yup, verified all combinations :)

**Pull request merged**
