### PR TITLE
Add Helm chart installer

### LINKED ISSUE #97: Create Helm chart for Event Router
Make it easier for users deploying vmware-event-router directly (on Kubernetes) by providing a Helm chart.Evaluate options for air-gapped deployments.

### PR DESCRIPTION
**Pull request by embano1**
## Summary

This PR adds the option to deploy the event router via Helm chart in an existing OpenFaaS environment (Knative to come).

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commmits related to your change
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [x] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

* Closes #97 

## Testing Verification

```bash
# before running these commands, create a override.yaml file for your environment specific settings as described in the README
helm repo add vmware-veba https://projects.registry.vmware.com/chartrepo/veba
"vmware-veba" has been added to your repositories

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "vmware-veba" chart repository
Update Complete. ⎈ Happy Helming!⎈

# using --devel flag since we are running from development branch
helm search repo event-router -l --devel
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
vmware-veba/event-router        v0.4.1-devel    development     The VMware Event Router is used to connect to v...

helm install -n vmware --create-namespace veba vmware-veba/event-router -f override.yaml --devel
NAME: veba
LAST DEPLOYED: Mon Nov  9 16:51:19 2020
NAMESPACE: vmware
STATUS: deployed
REVISION: 1
TEST SUITE: None

kubectl -n vmware logs deploy/router -f

 _    ____  ___                            ______                 __     ____              __
| |  / /  |/  /      ______ _________     / ____/   _____  ____  / /_   / __ \____  __  __/ /____  _____
| | / / /|_/ / | /| / / __  / ___/ _ \   / __/ | | / / _ \/ __ \/ __/  / /_/ / __ \/ / / / __/ _ \/ ___/
| |/ / /  / /| |/ |/ / /_/ / /  /  __/  / /___ | |/ /  __/ / / / /_   / _, _/ /_/ / /_/ / /_/  __/ /
|___/_/  /_/ |__/|__/\__,_/_/   \___/  /_____/ |___/\___/_/ /_/\__/  /_/ |_|\____/\__,_/\__/\___/_/

2020-11-09T15:51:21.210Z        INFO    [MAIN]  router/main.go:127      connecting to vCenter   {"address": "https://10.186.34.28"}
2020-11-09T15:51:21.211Z        INFO    [MAIN]  router/main.go:149      connected to OpenFaaS gateway   {"address": "http://gateway.openfaas:8080", "async": false}
2020-11-09T15:51:21.211Z        WARN    [METRICS]       metrics/server.go:59    no credentials found, disabling authentication for metrics server
2020-11-09T15:51:21.213Z        INFO    [METRICS]       metrics/server.go:131   starting metrics server {"address": "http://0.0.0.0:8082/stats"}
2020-11-09T15:51:21.226Z        DEBUG   [OPENFAAS]      types/controller.go:183 Syncing topic map
2020-11-09T15:51:21.410Z        INFO    [VCENTER]       vcenter/vcenter.go:170  checkpointing disabled, setting begin of event stream   {"beginTimestamp": "2020-11-09 15:51:21.313766 +0000 UTC"}
2020-11-09T15:51:23.014Z        DEBUG   [VCENTER]       vcenter/vcenter.go:271  no new events, backing off      {"delaySeconds": 1}
2020-11-09T15:51:24.290Z        DEBUG   [VCENTER]       vcenter/vcenter.go:271  no new events, backing off      {"delaySeconds": 2}
```

## Additional Information

n/a

### CODE REVIEW

**Comment by embano1** [comment]
@rguske @lamw can you please test? For an example overrides file, see https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/05c74da0165ec76325c4964153ca52d4bd964335/vmware-event-router/README.MD#example-deploy-into-new-namespace

**Comment by lamw** [comment]
LGTM, just verified on the latest TKG 1.2 Cluster running in my VMC setup :)

https://twitter.com/lamw/status/1325920731926986753

**Review by lamw — APPROVED** [review]
LGTM

**Comment by rguske** [comment]
Works like a charm! Great work @embano1 👏 
image

**Review by rguske — DISMISSED** [review]
LGTM
Functionality successfully tested:
```
2020-11-10T10:23:21.761Z        INFO    [OPENFAAS]      openfaas/openfaas.go:237        successfully invoked function   {"function": "powercli-reconfigure.openfaas-fn", "topic": "VmReconfiguredEvent", "retries": 0}
2020-11-10T10:23:21.762Z        INFO    [OPENFAAS]      openfaas/openfaas.go:192        finished processing of event    {"eventID": "4410e771-a48c-4842-bfc2-07efebe87f4d", "topic": "VmReconfiguredEvent"}
2020-11-10T10:23:21.825Z        INFO    [VCENTER]       vcenter/vcenter.go:301  invoking processor      {"eventID": "73fb3e86-9710-4623-b8f8-a05954c8c30b"}
```

**Review by lamw — APPROVED** [review]
LGTM

**Pull request merged**
