### PR TITLE
missing closing ```

### PR DESCRIPTION
**Pull request by klml**
## Summary

Paragraph "Deploy" had a missing closing ```

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe):

### CODE REVIEW

**Review by lamw — CHANGES_REQUESTED** [review]
Thanks for catching this @klml, we really apperciate it and fix!

Just small request, we have guidelines on commit message, which is then processed to generate good release notes. Could you please review https://vmweventbroker.io/community#guidelines and update commit message along with filing an Issue, which you can link back?

**Comment by klml** [comment]
@lamw sorry for my confusing git amen/rebase mess. I added the prefix `docs:`, but I dont understand why I should sign commits, I just merged like  d7808a6607dab288f02ab4320b8ea08a3c2b2264

**Comment by lamw** [comment]
Yea, looks like rebase may not have happened correctly before submitting ... I'm not git expert but looking at the commit, its including some of the newer changes prior to your original submission

**Comment by klml** [comment]
@lamw 

> Yea, looks like rebase may not have happened correctly before submitting

I had an issue with the rebase. I fixed it, so this PR has only 1 commit and this one is signed off, and prefixed. Di I miss anything else? thx

**Review by lamw — APPROVED** [review]
LGTM!

**Pull request merged**
