### PR TITLE
Adding the documentation for updating tls certificates

### PR DESCRIPTION
**Pull request by pksrc**
Adding md information for updating TLS certificate on VEBA. Setting and adhering to file naming convention "advanced-<topic>" with the aim of adding more self contained advanced topics that can be then added into a toc.

### CODE REVIEW

**Comment by embano1** [comment]
Thx PK! Can we create a generic `FAQ.md` doc and put these things into there?

**Comment by pksrc** [comment]
Yeah, i can do that. I'll have to reformat the document a little bit then. I hoped having self contained md would help with organizing documents but i can see how a single FAQ would serve well in a development/master branch.

**Comment by embano1** [comment]
Please not the change to the configuration files (see this PR https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/96)

**Comment by pksrc** [comment]
Sorry for the lack of updates. This will be addressed with the other updates that i'm putting together on the docs folder! Stay tuned :)

**Comment by pksrc** [comment]
Closing this for another change that is going into the docs folder. Changed to the config files have been noted and incorporated into the documentation for updating the certs

**Pull request closed without merging**
