### PR TITLE
Replace VMware Tanzu symbol on veba logo

### PR DESCRIPTION
**Pull request by rguske**
Closes: #707
Signed-off-by: Robert Guske <rguske@vmware.com>

## Summary

Replacing the VEBA logo with a new version which no longer has the VMware Tanzu logo.

veba_otto_the_orca_640x640_v2

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [x] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [ ] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [x] Please include any relevant screenshots and/or output as part of your testing
- [x] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [x] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes 
Closes: #707

## Additional Information

The PR will only update the Github repository with the new logo. Another PR has to be filed for the respective website changes.

### CODE REVIEW

**Comment by lamw** [comment]
@rguske It looks like this PR doesn't actually address the VEBA website?

I see at least 3x places in website where there's a unique version of the logo:
1) Website ICO - https://vmweventbroker.io/assets/img/veba-logo.png
2) Homepage Graphic - https://vmweventbroker.io/assets/img/heroes/veba_banner_md.png
3) Footer - https://vmweventbroker.io/assets/img/veba-logo.png

Please make sure to run Jekyll Docker Container locally on your PR (under /docs) and verify that all logos is now using the updated image

**Comment by rguske** [comment]
> @rguske It looks like this PR doesn't actually address the VEBA website?
> 
> I see at least 3x places in website where there's a unique version of the logo:
> 
> 1. Website ICO - https://vmweventbroker.io/assets/img/veba-logo.png
> 2. Homepage Graphic - https://vmweventbroker.io/assets/img/heroes/veba_banner_md.png
> 3. Footer - https://vmweventbroker.io/assets/img/veba-logo.png
> 
> Please make sure to run Jekyll Docker Container locally on your PR (under /docs) and verify that all logos is now using the updated image

This is intentional and the reason why I filed #709, because the website changes will possibly take more extra work to incorporate the new logo.
I already start working on the PR but I have to sync up with @pksrc on this as well.

**Comment by pksrc** [comment]
@rguske as a part of this PR, can you make product these images that we can use on the website? 
- Website ICO - https://vmweventbroker.io/assets/img/veba-logo.png / https://vmweventbroker.io/assets/img/favicon.ico 
- Homepage Graphic - https://vmweventbroker.io/assets/img/heroes/veba_banner_md.png 

If you can tackle Gimp related changes with this PR, I can handle the website related changes.

**Review by pksrc — APPROVED** [review]
LGTM

**Pull request merged**
